# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Aikido in Linz - Aiki-no-michi Linz
email: info@aiki-no-michi-linz.at
description: >- # this means to ignore newlines until "baseurl:"
  Der Verein Aikinomichi Linz wurde im April 2018 als unpolitischer, 
  nicht religiöser und nicht auf Gewinn ausgerichteter Verein gegründet. 
  Die Ziele des Vereins sind hauptsächlich die Förderung und Verbreitung 
  der japanischen Kampfkunst Aikido nach dem Reglement der Aikikai Foundation, 
  sowie die Pflege der Beziehungen mit anderen Vereinen und Organisationen 
  gleicher Zielsetzung. Unser technischer Leiter ist Christian Tissier Shihan 
  (8. Dan Aikikai) wir arbeiten eng mit seinem Schüler Stéphane Goffin 
  (6. Dan Aikikai) zusammen.

baseurl: "/aikinomichi-linz" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
show_social_icons: true
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
sass:
  sass_dir: css
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
